---
abstract: 'A URI type library for Mouse'
author:
  - 'NAKAGAWA Masaki <masaki@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.94
  Test::UseAllModules: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MouseX-Types-URI
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Mouse: 0.40
  MouseX::Types: 0.02
  MouseX::Types::Path::Class: 0.06
  Scalar::Util: 1.14
  URI: 0
  URI::FromHash: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/masaki/MouseX-Types-URI.git
version: 0.03
